Explicitly set C++ standard to use
Build with GCC 5.1 failed with error:
[  185s] ../../../dali/public-api/math/compile-time-math.h:121:22: error: the value of 'Dali::Epsilon<1u>::value' is not usable in a constant expression
[  185s]    static const float value = 10.0f * Epsilon< Power< 10, Log< N, 10 >::value >::value / 10 >::value;

Which is fixed if we set C++ standard explicitly.

Change-Id: Id60c91a1300d5f740c5ad8900c9af320f9d52395
Signed-off-by: Yury Usishchev <y.usishchev@samsung.com>